### ISSUE TITLE
Pointer error

### ISSUE THREAD

**Issue by amueller** [SalvaEB/mask_word_cloud#1]
I tried to bench your code a bit against mine.
When changing the step-size, I ran into this:

```
../src/maskwc -m alice_mask.png -R 255 -G 255 -B 255 -o background_alice peace.txt -s 1        
*** Error in `../src/maskwc': munmap_chunk(): invalid pointer: 0x00007f61e65c3010 ***
```

**Comment by SalvaEB** [comment]
I didn't have an error but valgrind said there was an invalid write. Effectively there as a bad check which seems solved now. Update and try it again :)

**Comment by amueller** [comment]
Thanks, I'll try :)
